# Generated by Django 4.2.2 on 2023-07-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_admin',
        ),
    ]
